<?php

$img = fn (string $id, string $seed, string $alt) => [
    'id' => $id,
    'url' => "https://images.unsplash.com/{$seed}?auto=format&fit=crop&w=1400&q=80",
    'alt' => $alt,
];

$tags = [
    ['id' => 't1', 'name' => 'STM32', 'slug' => 'stm32'],
    ['id' => 't2', 'name' => 'UART', 'slug' => 'uart'],
    ['id' => 't3', 'name' => 'DMA', 'slug' => 'dma'],
    ['id' => 't4', 'name' => 'ESP32', 'slug' => 'esp32'],
    ['id' => 't5', 'name' => 'FreeRTOS', 'slug' => 'freertos'],
    ['id' => 't6', 'name' => 'C', 'slug' => 'c'],
];

return [
    'site' => [
        'name' => 'Mehmet Dora',
        'initials' => 'MD',
        'role' => 'Embedded Systems & Software Developer',
        'location' => 'Istanbul, Turkey',
        'title' => 'Mehmet Dora | Embedded Systems & Personal Website',
        'description' => 'Embedded systems, low-level programming, projeler, teknik yazılar ve kişisel paylaşımlar.',
        'profile_image' => '/profile.svg',
        'links' => [
            'github' => 'https://github.com/Mehmetdora',
            'linkedin' => 'https://linkedin.com/',
            'telegram' => 'https://t.me/',
            'email' => 'mailto:mehmetdora333@gmail.com',
            'cv' => '/cv/pdf',
        ],
        'nav' => [
            ['title' => 'Home', 'href' => '/'],
            ['title' => 'About', 'href' => '/about'],
            ['title' => 'Projects', 'href' => '/projects'],
            ['title' => 'Blog', 'href' => '/blog'],
            ['title' => 'Resume', 'href' => '/cv'],
            ['title' => 'My Life', 'href' => '/life', 'special' => true],
        ],
    ],
    'home' => [
        'top_skills' => ['C / C++', 'Embedded C', 'STM32 / ESP32', 'RTOS / FreeRTOS', 'UART / SPI / I2C', 'CAN-BUS', 'PCB & Debug', 'Firmware Architecture'],
        'expertise' => [
            ['title' => 'Embedded Systems', 'description' => 'STM32 ve ESP32 tabanlı mikrodenetleyici projeleri, sensör okuma, çevresel birimler ve düşük seviye firmware geliştirme.', 'icon' => 'cpu'],
            ['title' => 'Real-Time Software', 'description' => 'Interrupt-driven mimari, FreeRTOS task yapısı, UART DMA, timer tabanlı işler ve zaman kritik kontrol akışları.', 'icon' => 'timer'],
            ['title' => 'Communication Protocols', 'description' => 'UART, SPI, I2C, CAN-BUS ve BLE gibi haberleşme katmanlarında paket yapısı, debug ve güvenilir veri akışı.', 'icon' => 'radio'],
            ['title' => 'Code & Project Documentation', 'description' => 'Teknik yazılar, proje günlükleri ve öğrendiklerimi anlaşılır hale getiren içerik üretimi.', 'icon' => 'code'],
        ],
        'tech_stack' => ['C', 'C++', 'STM32', 'ESP32', 'Arduino', 'FreeRTOS', 'UART', 'SPI', 'I2C', 'CAN', 'TypeScript', 'Next.js', 'Laravel', 'PostgreSQL', 'Git', 'Linux'],
    ],
    'about' => [
        'stats' => [
            ['value' => 'CENG', 'label' => 'Computer Engineering'],
            ['value' => 'STM32', 'label' => 'Main MCU Focus'],
            ['value' => 'ESP32', 'label' => 'IoT & Wireless'],
            ['value' => 'C/C++', 'label' => 'Core Languages'],
        ],
        'hobbies' => [
            ['title' => 'Elektronik ve maker projeleri', 'description' => 'Yeni sensörler, geliştirme kartları ve küçük prototiplerle uğraşmak; öğrendiğim şeyi fiziksel bir çıktıya dönüştürmek.', 'icon' => 'cpu'],
            ['title' => 'Teknik okuma ve not tutma', 'description' => 'Datasheet, uygulama notu, proje dokümantasyonu ve öğrendiğim konuları daha sonra dönüp bakabileceğim şekilde yazmak.', 'icon' => 'book'],
            ['title' => 'Yürüyüş ve keşif', 'description' => 'Kafayı toparlamak, yeni fikirleri sindirmek ve uzun teknik oturumlardan sonra ritmi yeniden bulmak için yürümek.', 'icon' => 'route'],
            ['title' => 'Müzik, fotoğraf ve oyun', 'description' => 'Teknik üretimin dışında müzik dinlemek, anları kaydetmek ve oyunlarla zihni biraz başka bir moda almak.', 'icon' => 'music'],
        ],
        'education' => [
            ['degree' => 'Computer Engineering', 'period' => 'Devam ediyor', 'org' => 'Bilgisayar mühendisliği öğrencisi'],
            ['degree' => 'Embedded Systems Self-Lab', 'period' => 'Sürekli', 'org' => 'STM32, ESP32, FreeRTOS, haberleşme protokolleri ve proje tabanlı öğrenme'],
        ],
    ],
    'tags' => $tags,
    'posts' => [
        [
            'id' => 'p1',
            'title' => 'STM32 UART DMA Receive Mantığını Kurmak',
            'slug' => 'stm32-uart-dma-receive',
            'summary' => 'Interrupt yükünü azaltan, buffer yönetimi daha temiz bir UART DMA yaklaşımı.',
            'cover' => $img('m1', 'photo-1518770660439-4636190af475', 'Elektronik devre kartı'),
            'tags' => ['stm32', 'uart', 'dma', 'c'],
            'status' => 'published',
            'visibility' => 'public',
            'published_at' => '2026-05-14',
            'updated_at' => '2026-05-18',
            'reading_time' => 6,
            'content' => [
                ['type' => 'paragraph', 'text' => 'UART DMA, gömülü projelerde CPU üzerindeki gereksiz interrupt yükünü azaltmak için çok kullanışlıdır.'],
                ['type' => 'heading', 'text' => 'Neden DMA?'],
                ['type' => 'paragraph', 'text' => 'Sürekli veri akan sistemlerde byte byte interrupt almak yerine çevresel birimin belleğe yazmasına izin vermek daha sakin bir akış sağlar.'],
                ['type' => 'callout', 'title' => 'Dikkat', 'text' => 'Callback içinde uzun işlem yapmak yerine bayrak set edip işi task veya main loop tarafına bırak.'],
                ['type' => 'code', 'language' => 'c', 'filename' => 'uart_dma.c', 'code' => "HAL_UARTEx_ReceiveToIdle_DMA(&huart2, rxBuffer, RX_BUFFER_SIZE);\n__HAL_DMA_DISABLE_IT(huart2.hdmarx, DMA_IT_HT);"],
            ],
        ],
        [
            'id' => 'p2',
            'title' => 'FreeRTOS Task Tasarımında İlk Prensipler',
            'slug' => 'freertos-task-tasarimi',
            'summary' => 'Task, queue ve semaphore kararlarını sade tutmak için pratik bir yaklaşım.',
            'cover' => $img('m2', 'photo-1558494949-ef010cbdcc31', 'Sunucu ve elektronik altyapı'),
            'tags' => ['stm32', 'freertos', 'c'],
            'status' => 'published',
            'visibility' => 'public',
            'published_at' => '2026-05-09',
            'reading_time' => 5,
            'content' => [
                ['type' => 'paragraph', 'text' => 'FreeRTOS tasarımında hedef, her işi task yapmak değil, sistemi okunabilir sorumluluklara ayırmaktır.'],
                ['type' => 'heading', 'text' => 'Task sınırları'],
                ['type' => 'quote', 'text' => 'Bir task gerçek bir zamanlama ihtiyacını veya bağımsız sorumluluğu temsil etmeli.'],
            ],
        ],
        [
            'id' => 'p3',
            'title' => 'ESP32 BLE Advertisement Paketlerini Okumak',
            'slug' => 'esp32-ble-advertisement',
            'summary' => 'BLE broadcaster projemde reklam paketlerini parse ederken öğrendiklerim.',
            'cover' => $img('m3', 'photo-1550751827-4bd374c3f58b', 'Kablosuz ağ ve devre temsili'),
            'tags' => ['esp32', 'c'],
            'status' => 'published',
            'visibility' => 'public',
            'published_at' => '2026-04-22',
            'reading_time' => 4,
            'content' => [
                ['type' => 'paragraph', 'text' => 'BLE advertisement paketleri küçük görünür ama doğru ayrıştırma için alan uzunluklarını disiplinli takip etmek gerekir.'],
                ['type' => 'code', 'language' => 'cpp', 'filename' => 'packet_parser.cpp', 'code' => "while (index < payloadLength) {\n  const uint8_t fieldLength = payload[index++];\n  const uint8_t fieldType = payload[index++];\n}"],
            ],
        ],
    ],
    'projects' => [
        [
            'id' => 'pr1',
            'title' => 'ESP32 BLE Broadcaster',
            'slug' => 'esp32-ble-broadcaster',
            'summary' => 'ESP32 ile BLE advertisement yayınlayan ve paket alanlarını ayrıştıran küçük embedded lab projesi.',
            'cover' => $img('pm1', 'photo-1581092160607-ee22621dd758', 'ESP32 ve sensörler'),
            'technologies' => ['C++', 'ESP32', 'BLE', 'Arduino', 'ESP32 DevKit', 'USB serial', 'Logic analyzer', 'Arduino IDE', 'Serial Monitor', 'Git'],
            'status' => 'in-progress',
            'visibility' => 'public',
            'featured' => true,
            'tags' => ['esp32', 'c'],
            'github' => 'https://github.com/',
            'content' => [
                ['type' => 'paragraph', 'text' => 'Bu proje kişisel embedded lab için BLE tarafında temel yayın ve paket okuma akışını anlamaya odaklanıyor.'],
                ['type' => 'heading', 'text' => 'Öğrendiklerim'],
                ['type' => 'list', 'items' => ['Advertisement alan yapısı', 'Payload uzunluk kontrolü', 'Seri port üzerinden debug akışı']],
            ],
        ],
        [
            'id' => 'pr2',
            'title' => 'STM32 Sensor Dashboard',
            'slug' => 'stm32-sensor-dashboard',
            'summary' => 'STM32 üzerinden sensör okumalarını toplayıp seri arayüzle görselleştiren dashboard altyapısı.',
            'cover' => $img('pm2', 'photo-1581093588401-fbb62a02f120', 'Mikrodenetleyici geliştirme masası'),
            'technologies' => ['C', 'STM32', 'UART', 'DMA', 'STM32F407 Discovery', 'HC-SR04', 'Breadboard', 'STM32CubeIDE', 'KiCad'],
            'status' => 'planned',
            'visibility' => 'public',
            'featured' => true,
            'tags' => ['stm32', 'uart', 'dma'],
            'content' => [
                ['type' => 'paragraph', 'text' => 'Planlanan bu proje, sensör verisini daha temiz bir veri hattı üzerinden izlemeyi hedefliyor.'],
            ],
        ],
        [
            'id' => 'pr3',
            'title' => 'FreeRTOS Mini Scheduler Lab',
            'slug' => 'freertos-mini-scheduler-lab',
            'summary' => 'FreeRTOS task ve queue örneklerini deneysel küçük uygulamalarla belgeleyen çalışma.',
            'cover' => $img('pm3', 'photo-1516321318423-f06f85e504b3', 'Kod ve geliştirme ortamı'),
            'technologies' => ['C', 'FreeRTOS', 'STM32', 'STM32 Nucleo', 'LED matrix', 'STM32CubeIDE'],
            'status' => 'completed',
            'visibility' => 'public',
            'featured' => true,
            'tags' => ['freertos', 'stm32', 'c'],
            'content' => [
                ['type' => 'paragraph', 'text' => 'Küçük task örnekleriyle RTOS zihniyetini pratikte oturtmak için hazırlanmış bir çalışma.'],
            ],
        ],
    ],
    'life' => [
        [
            'id' => 'l1',
            'excerpt' => 'Kablolar, not defterleri ve yarım kalan modüller sonunda biraz daha yaşanabilir hale geldi.',
            'images' => [
                $img('lm1', 'photo-1516321497487-e288fb19713f', 'Çalışma masası ve laptop'),
                $img('lm1b', 'photo-1498050108023-c5249f4df085', 'Laptop ve çalışma masası'),
                $img('lm1c', 'photo-1518770660439-4636190af475', 'Elektronik kart yakın plan'),
            ],
            'published_at' => '2026-05-12',
            'location' => 'İstanbul',
        ],
        [
            'id' => 'l2',
            'excerpt' => 'Uzun bir çalışma gününden sonra kulaklık, sakin bir rota ve kafayı boşaltan birkaç şarkı.',
            'images' => [$img('lm2', 'photo-1500530855697-b586d89ba3ee', 'Gün batımında yürüyüş yolu')],
            'published_at' => '2026-05-19',
            'location' => 'İstanbul',
        ],
        [
            'id' => 'l3',
            'excerpt' => 'Projeler, sınavlar ve yapılacaklar arasında kısa ama iyi gelen bir buluşma.',
            'images' => [$img('lm3', 'photo-1529156069898-49953e39b3ac', 'Arkadaşlarla dışarıda buluşma')],
            'published_at' => '2026-05-08',
            'location' => 'İstanbul',
        ],
        [
            'id' => 'l4',
            'excerpt' => 'Düzenli kalmaya çalıştığım, küçük hedeflerle ilerleyen spor rutini.',
            'images' => [$img('lm4', 'photo-1517836357463-d25dfeac3438', 'Spor salonu ekipmanları')],
            'published_at' => '2026-04-28',
        ],
    ],
];
